### ISSUE TITLE
'Simulator Bug' after Hold.

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/A320neo#10]
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues
undefined symbol: hold_pattern:
 at C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasal/FMGC/fmgc
_loop.nas, line 867
  called from: C:/Users/Redpath/Documents/GitHub/MY_FGDATA/Aircraft/A320neo/Nasa
l/FMGC/fmgc_loop.nas, line 3137
You have encountered a bug in the A320neo model.
Please, report it along with the above message and description of what you
were doing when it happened to https://github.com/FGMEMBERS/A320neo/issues

Once the next waypoint is one with a hold, then the console fills with these errors and the red master caution beeps 'Simulator Bug'

**Comment by jan-hudec** [comment]
The fix turned out to be easy; the needed nasal source was simply missing from the set.

How hold can be flow to and it flies the hold. It needs more testing and I am sure there are more bugs (I already know one: it does not always draw the correct pattern—I chose left orbit, it flew left orbit, but drew right), but at least it can be tested now.

**Comment by legoboyvdlp** [comment]
Thats good.
By the way, it flies a circle, not a 'racetrack'. Is that correct behavior?

**Comment by jan-hudec** [comment]
@legoboyvdlp, when I tested it it flew the expected oval track, but only at sufficiently low speed. It _looked like_ it tries to fly the track with a fixed shape and if the speed is too high, overshoots and ends up turning in circles and variously offset loops. Which is not correct behaviour, because the pattern is defined by time, not fixed dimensions.
