### ISSUE TITLE
Bug Report #2: Automatic ground spoilers deploy during take off

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS/A320neo#13]
Filled via the <a href="https://docs.google.com/forms/d/1GG-VoX1awQQQ5FZvZYc61GFA7lchDOhHRHhPZDigxd8/viewform">bug report form</a>
User: Legoboy. 
Reproducible: Yes. Everytime
OS: Windows 7 Home Premium 64bit
FG Version: Git. Aircraft from FGMEMBERS
Affects: A320neo, but not A319/A318

---

> Legobody Wrote: 
> When I am on the takeoff roll, ground spoilers deploy automatically.
> This is also present in the ""dev"" (private) A330-200 and the MEMBERS 330-200.
> Seems to be at V1, not sure.

**Comment by legoboyvdlp** [comment]
Well, that is, I did not test 19 or 21. There is no A318neo, for some reason, IRL.

**Comment by jan-hudec** [comment]
Duplicate of #9.

**Comment by FGDATA** [comment]
Since this is already been talked about in #9 I am closing this double. @IAHM-COL
