### ISSUE TITLE
Atypical [TAB] Behavior

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS/A320neo#14]
Bug reported on Curtis' Forum by F15
http://forum.flightgear.org/viewtopic.php?f=4&t=12903&start=465#p263284

---

> Hi there seems to be a problem with mouse control on the A320neo (all A319, A320 and A321).
> When [TAB] is pressed, the cross that signals flight control does not appear. [TAB] does not seem to be detected.
> Is this an internal problem with the A320neo or a FlightGear bug? And how can I fix this problem?
> P.s. the [TAB] works fine with Boeing aircraft

**Comment by jan-hudec** [comment]
General FlightGear issue, not A320.

[TAB] works just fine in A320neo, unless you have a canvas dialog open and focused. With focused canvas dialog it does not work with any plane that has it (which includes the 777, 757 and many other models).

**Comment by FGDATA** [comment]
Just to make sure we are in the same board:
[TAB] in FG, for most planes switches mouse behavior, but in A320neo it does not?
Does how it works for me. 
Some say [TAB] has other functions to the A320neo. Other's say it doesn't. So I am uncertain here. 

If I am allowed to weight in, I think standardizing the behavior of the [TAB] is all together a good thing -- one less prone to confuse new users to a plane. Could the [TAB] function in the A320neo  be assigned another key stroke, and release [TAB] to its mouse-toggling behavior?

This is something that is more a design issue than a "problem" or so I feel

What do you think @jan-hudec 

Yours,
@IAHM-COL

**Comment by FGDATA** [comment]
@jan-hudec 

You are correct. I just verified with the latest A320neo here in FGMEMBERS, FG 3.7
[TAB] behavior is O,K. Just as expected, cycling thru mouse modes.

Thanks for the note, I withdraw my comments above and also close this invalid issue

Best
@IAHM-COL

**Comment by legoboyvdlp** [comment]
Hi @IAHM-COL 
Just to confirm, this bug was indeed present in the original Omega A320, and [TAB] cycled the autobrake. However, now, autobrake has no key, and Tab works as expected.
Cheers!
Jonathan
