### ISSUE TITLE
Basic copilot functionality

### ISSUE THREAD

**Issue by choyiny** [FGMEMBERS/A320neo#2]
It seems like copilot can do nothing but sit in the cockpit and watch the plane flown by the pilot. Not even look at instruments (They are all displayed as shutdown). Looking to add/fix co-pilot functionality in the A320neo.
- [ ] Enable basic functions for co-pilot (i.e. instruments lighting up for copilot)
- [ ] Enable co-pilot to monitor some instruments (primary
  flight controls, throttle, mixture, elevator trim, flaps, brakes,
  cockpit switches, part of the radio stack and instrument settings)
- [ ] Enable co-pilot for A319 and A321

**Comment by choyiny** [comment]
Seem to have found missing files... Unable to locate the Generic folder for dual control tools. Don't know what it does please help if anyone knows

```
<nasal>
    <walk>
        <file>Aircraft/A320neo/Nasal/walk.nas</file>
    </walk>
    <!-- Dual control -->
    <dual_control_tools>
        <file>Aircraft/Generic/DualControl/dual-control-tools.nas</file>
    </dual_control_tools>
    <aircraft_dual_control>
        <file>Aircraft/A320neo/DualControl/a320-dual-control.nas</file>
    </aircraft_dual_control>
    <dual_control>
        <file>Aircraft/Generic/DualControl/copilot-dual-control.nas</file>
    </dual_control>
</nasal>
```

**Comment by FGDATA** [comment]
I'll see if these are to be found in past snapshots

**Comment by FGDATA** [comment]
:) (?) I see them all as expected

**Comment by choyiny** [comment]
I suggest you add the files into /DualControl/ and change the path in the copilot-set.xml file.

**Comment by FGDATA** [comment]
https://github.com/FGMEMBERS/A320neo/blob/master/Nasal/walk.nas
https://github.com/FGMEMBERS/A320neo/blob/master/DualControl/a320-dual-control.nas

the Path Aircraft/Generic/DualControl resides outside the A320neo directory. In FGDATA

both nasals are there too :)

http://sourceforge.net/p/fgdata/submodules/ci/next/tree/Aircraft/Generic/DualControl/

**Comment by FGDATA** [comment]
> I suggest you add the files into /DualControl/ and change the path in the copilot-set.xml file.

That would nt change it, in the sense that it will not achieve implementing functionality not working as it is.
The advantage of calling the generic is that if changes occur globally, it will still apply.

I believe, if we were to implement additional (local) functionality in addition to the basic provided in the generic, then copying makes sense. Which is currently not our case... 

Best,
IH-cOL

**Comment by FGDATA** [comment]
a good comparison case is the dc6, I believe. 
At least the copilot can monitor instruments. If I recall correctly, there he/she couldn't gain control of the craft either

**Comment by choyiny** [comment]
> fr/Douglas DC-3-C47, pilot and copilot can control aircraft, and passenger 1 to 4 (dc-3, dc-3-copilot, dc-3-psg1, dc-3-psg2, dc-3-psg3, dc-3-psg4). Available in GIT.

http://wiki.flightgear.org/Dual_control

I will follow DC-3 to copy the fgdata dualcontrol modules to the folder, and then looking into how they managed to make dualcontrol work.

**Comment by FGDATA** [comment]
I see.
I am "kinda" remembering that this may have never been implemented in the first place ...

It may just be missing code (to be completed/created)

**Comment by choyiny** [comment]
See 85681c5
Awaiting test
