### ISSUE TITLE
How can I add this plane to my flightgear

### ISSUE THREAD

**Issue by ayushdeolasee** [FGMEMBERS/A320neo#24]
I have cloned this directory but when I try to add this in my add ons in flight gear it gives me the error No aircraft found in the folder 'Path'-add anyway? How can I fix this issue?

**Comment by FGDATA** [comment]
If you had cloned this aircraft, you have to add the **parent** directory where the aircraft resides to your flightgear's seek path for aircrafts. 
With command line it looks like
`--fg-aircraft=/path/to/Aircrafts`

**Comment by ayushdeolasee** [comment]
So how do I add it to my flightgear

**Comment by ayushdeolasee** [comment]
Which is the folder that I need to go into to add it

**Comment by wlbragg** [comment]
>No aircraft found in the folder

Your pointing at the wrong folder. What is the path to your aircraft folder?
C://???/???/???

**Comment by ayushdeolasee** [comment]
I ran the command that you gave me and this is the error that I got zsh: no such file or directory: --fg-aircraft=/path/to/Aircrafts

**Comment by ayushdeolasee** [comment]
I am not sure what path because I have installed all my aircrafts from the app itself so it has to be the default folder.

**Comment by wlbragg** [comment]
>/path/to/Aircrafts

That does not mean literally use path/to/Aircrafts.
It means point at the folder you put the aircraft in. If you downloaded the aircraft from this repository then you did not "installed all my aircrafts from the app itself". This is a repository, not an app. You downloaded a zip file called A320neo.zip or cloned it using git and placed it in a folder on a drive somewhere? You have to know where you put it or you cannot use it. You have to know where you put it.
Where did you put the aircraft you downloaded from here?
It will be in a physical location on your hard drive. We can't teach you how to get around in your computer files and drives. That is basics you have to know in order to use your computer effectively for anything!

**Comment by ayushdeolasee** [comment]
it's on my home drive on my mac

**Comment by wlbragg** [comment]
You need to provide the complete path to the folder that contains the new aircraft you want to use.
My aircraft folder is at /home/joe/FGFS/Aircraft/A320neo
I can't help you if you can't be more specific than "my home drive on my mac", sorry!

**Comment by FGDATA** [comment]
Hi, 
I also think @pypdeveloper is using my example as a complete command, but it is not intended so,

I'll recommend he revises this content:

http://wiki.flightgear.org/Command_line_options

**Comment by ayushdeolasee** [comment]
The airplane is in User/username/A320neo

**Comment by ayushdeolasee** [comment]
I have this same issue with all aircraft is it something with flightgear?

**Comment by FGDATA** [comment]
> I have this same issue with all aircraft is it something with flightgear?

Not necesarily. It is more probably due to your still figuring out how to let flightgear know you have additional aircrafts. (In this sense, the "something" with flightgear is that it is not very intuitive at this respect).

Let me ask, how do you launch flightgear? Do you use the Qt5 launcher, that looks like this?

![image](http://wiki.flightgear.org/images/thumb/c/ca/Qt_launcher_for_FlightGear_2018.2_on_Windows_10_aircraft.jpg/760px-Qt_launcher_for_FlightGear_2018.2_on_Windows_10_aircraft.jpg)

**Comment by ayushdeolasee** [comment]
Yes

**Comment by FGDATA** [comment]
Hi @pypdeveloper 

I don't use that launcher. I don't think is a well thought part of FlightGear. But I wonder if there in "settings" on the left, can you set additional aircraft directories. 
If so, then point  your settings to the parent directory where you are storing other aircraft.

Second question:

Did you clone the repository or did you download the zip file and unzipped?

**Comment by FGDATA** [comment]
@pypdeveloper 

Actually not,
The option seem to be in the add-ons. The very last option of the menu of the left. 
There you see **_"Additional aircraft folders (Add+)"_**

![example](https://imgur.com/BnaCMaF.png)

Click the Add + and follow from there. Add the parent directory that holds your git cloned aircraft

Also, 
If you happen to zip download. you will need to rename the unpacked directory, removing the "-master" part of every aircraft folder name


Hopefully this sets you in the right track.
Let us know.

**Comment by ayushdeolasee** [comment]
Okay so no, I have cloned and taken a zip file and unzipped it in to a folder and my screen looks different for the ad-on's page

**Comment by ayushdeolasee** [comment]
I did the exact same thing with clicking the add button but it give's me the error

**Comment by FGDATA** [comment]
After unzipping, rename the aircraft directory
example:

`A320neo-master`

to 

`A320neo`

(everytime, remove the `-master` after unzipping)

Can you show your screenshot in Addons?

**Comment by ayushdeolasee** [comment]
![Screenshot 2020-05-18 at 8 28 52 AM](https://user-images.githubusercontent.com/43103441/82170390-eb3e1780-98e1-11ea-93fc-ceb37be22c8d.png)
I don't have the modules page

**Comment by FGDATA** [comment]
@pypdeveloper 
The option is there: 
![bitmap](https://user-images.githubusercontent.com/10859459/82170582-ba29fc80-9879-11ea-8b3c-3083a09fdbc4.png)
Additional aircraft folders, **Add +**
See arrow.

Start there. Follow prompts
Indicate the parent directory (where you unzipped the aircrafts)

Also, as indicated above, rename the dir.
Try again

(it might need you to restart the launcher, or not, simply going back to "Aircraft" it might just work)

Let us know

**Comment by ayushdeolasee** [comment]
I tired but it's not working it's giving that same error that, No aircraft found in the folder 'Path'-add anyway?

**Comment by FGDATA** [comment]
Add anyways. 
And did you rename the aircraft after unzip?

**Comment by ayushdeolasee** [comment]
Yes I did add anyways it's not working and I have cloned and unzipped many files with and without the --master and I am also cloning the files.

**Comment by FGDATA** [comment]
that is unsettling
Screenshots might help

**Comment by ayushdeolasee** [comment]
![Screenshot 2020-05-18 at 8 52 41 AM](https://user-images.githubusercontent.com/43103441/82171467-04949300-98e5-11ea-8584-d41c782d2e5d.png)
Here you go this is the error

**Comment by FGDATA** [comment]
Yes
I suggest you are going to add the **Parent** directory
That is, don't select the aircraft, but the directory that contains the aircraft

Example

Lets say

`/Users/MyName/Aircrafts/A320neo`

Don't select the Directory `A320neo` before adding
Try instead selecting the `Aircrafts` directory. Which is the parent. (and in that parent, you can drop as many planes as you can find

Let me know if that helps

**Comment by ayushdeolasee** [comment]
Thanks it worked, thanks so much

**Comment by FGDATA** [comment]
kuddos. enjoy testing aircrafts

Best
@IAHM-COL
